### ISSUE TITLE
Red Hat container registry image is out of date

### ISSUE THREAD

**Issue by snecklifter** [PureStorage-OpenConnect/tripleo-deployment-configs#7]
Hello,

I appreciate this might not be the right place to report this however the images in the Red Hat registry are out of date for OSP 13.

https://catalog.redhat.com/software/containers/purestorage/openstack-cinder-volume-pure-rhosp-13/5c923c70ac3db9732a5ec67f

As it appears that these get built and published using the dockerfile in this repo, is it possible to pick this up and get them updated?

**Comment by sdodsley** [comment]
@snecklifter Not sure what you mean by `out-of-date`... 
These images are automatically rebuilt by Red Hat should any of the underlying base images change. This suggests that there hasn't been a change to the base image, nor has there been a change to the Pure Cinder driver, however, I have forced a new build. 
If there are still security errors you will need to ask Red Hat to update the base image we are required to use for Cinder in RHOSP13.
BTW love your github handle - great beer and I see you are from the place II went to University - great place.

**Comment by snecklifter** [comment]
@sdodsley thanks for the quick response and for the new build! The base image should be the latest available and this has certainly changed in the last 9 months. Do you have a version/tag for the base image Red Hat have specified so I can follow this up? 

Sheffield is lovely, why did you ever leave? As for Snecklifter, I chose the handle back in the late 90s before they moved production and sadly its a shadow of its former self. I remember the days when it was so dark you couldn't see through the bottle...

**Comment by sdodsley** [comment]
@snecklifter the new version is built. Appears like there are less security issues now, so something changed in the base image. Not sure why the auto-builder didn't kick in.
